fragment PostsParts on Posts {
  __typename
  title
  description
  phone
  phones {
    __typename
    number
    timeLabel
    blockLabel
  }
  moreInfo
  location
  scheduleMonTue
  scheduleWedFri
  scheduleSaturday
  email
  whatsapp
  links
}
